//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineDatabase.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicineDatabase.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday: .
        /// </summary>
        public static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRI:.
        /// </summary>
        public static string DayFridayShort {
            get {
                return ResourceManager.GetString("DayFridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday: .
        /// </summary>
        public static string DayHoliday {
            get {
                return ResourceManager.GetString("DayHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOL:.
        /// </summary>
        public static string DayHolidayShort {
            get {
                return ResourceManager.GetString("DayHolidayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday: .
        /// </summary>
        public static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MON..
        /// </summary>
        public static string DayMondayShort {
            get {
                return ResourceManager.GetString("DayMondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday: .
        /// </summary>
        public static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAT:.
        /// </summary>
        public static string DaySaturdayShort {
            get {
                return ResourceManager.GetString("DaySaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday: .
        /// </summary>
        public static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUN:.
        /// </summary>
        public static string DaySundayShort {
            get {
                return ResourceManager.GetString("DaySundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday: .
        /// </summary>
        public static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU:.
        /// </summary>
        public static string DayThursdayShort {
            get {
                return ResourceManager.GetString("DayThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday: .
        /// </summary>
        public static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUE:.
        /// </summary>
        public static string DayTuesdayShort {
            get {
                return ResourceManager.GetString("DayTuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday: .
        /// </summary>
        public static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WED:.
        /// </summary>
        public static string DayWednesdayShort {
            get {
                return ResourceManager.GetString("DayWednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: .
        /// </summary>
        public static string DistanceText {
            get {
                return ResourceManager.GetString("DistanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition.
        /// </summary>
        public static string FilterComposition {
            get {
                return ResourceManager.GetString("FilterComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraindications.
        /// </summary>
        public static string FilterContraindications {
            get {
                return ResourceManager.GetString("FilterContraindications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indications.
        /// </summary>
        public static string FilterIndications {
            get {
                return ResourceManager.GetString("FilterIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions.
        /// </summary>
        public static string FilterInteractions {
            get {
                return ResourceManager.GetString("FilterInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FilterName {
            get {
                return ResourceManager.GetString("FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Effects.
        /// </summary>
        public static string FilterSideEffect {
            get {
                return ResourceManager.GetString("FilterSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Substances.
        /// </summary>
        public static string FilterSubstances {
            get {
                return ResourceManager.GetString("FilterSubstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug database:
        ///
        ///
        ///Search window:
        ///Before the search, it is possible to write down the health problems that the person already suffers from so that it is taken into account during the search. If you enter health data and one of the found medicines would be problematic and could cause you health complications, this medicine will be colored differently (in red).
        ///
        ///You can also search for medicines in this window. The search is possible according to several filters that you can choose.
        ///Without the text fill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MedicineHelpText {
            get {
                return ResourceManager.GetString("MedicineHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My health.
        ///
        ///In this window, you will find information about your health that you have filled in and medications that you have added to the list, which you can, for example, print out and take with you to the pharmacy. You can edit the number or remove medicines from the list.
        ///
        ///The information you have filled in regarding your health is taken into account when searching for medicines. Those that could cause you problems will be colored differently. However, the information is for informational purposes o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MyHealthHelpText {
            get {
                return ResourceManager.GetString("MyHealthHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location: 
        ///.
        /// </summary>
        public static string MyLocationTooltip {
            get {
                return ResourceManager.GetString("MyLocationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found. Please try again..
        /// </summary>
        public static string noSearchPillsResultText {
            get {
                return ResourceManager.GetString("noSearchPillsResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying the nearest pharmacies in the area
        ///
        ///
        ///Window Location:
        ///In this window, you must enter the approximate address where you are located. Street, number, city and postal code number.
        ///It is not necessary to enter everything, but at least something must be filled in.
        ///Subsequently, it is necessary to confirm this position with the button. A marker of your location will appear on the map. After clicking to confirm the location, the button to display pharmacies will be available.
        ///This button will red [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PharmaciesHelpText {
            get {
                return ResourceManager.GetString("PharmaciesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H - hours
        ///D - days
        ///W - weeks
        ///M - months.
        /// </summary>
        public static string PillDetailExpirationTooltipText {
            get {
                return ResourceManager.GetString("PillDetailExpirationTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUKL code: .
        /// </summary>
        public static string PillListItem_SUKLCode {
            get {
                return ResourceManager.GetString("PillListItem.SUKLCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!
        ///
        ///According to your health information, this medicine may be problematic for you and cause you health problems..
        /// </summary>
        public static string ProblemPillTolltipText {
            get {
                return ResourceManager.GetString("ProblemPillTolltipText", resourceCulture);
            }
        }
    }
}
